// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZQIEra7xFUFwOrZP_NYRpeSP3WTcY-E',
    appId: '1:175049490367:web:66e5706b7bc07d5ff4ab0a',
    messagingSenderId: '175049490367',
    projectId: 'ethmar-95aaf',
    authDomain: 'ethmar-95aaf.firebaseapp.com',
    storageBucket: 'ethmar-95aaf.firebasestorage.app',
    measurementId: 'G-HRWRQZH0FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQqyCXb0xR_NiHyk-Rmfp9QINiwCB1Dc',
    appId: '1:175049490367:android:2e48bade2bc03261f4ab0a',
    messagingSenderId: '175049490367',
    projectId: 'ethmar-95aaf',
    storageBucket: 'ethmar-95aaf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZQIEra7xFUFwOrZP_NYRpeSP3WTcY-E',
    appId: '1:175049490367:web:2f1649c763016ef0f4ab0a',
    messagingSenderId: '175049490367',
    projectId: 'ethmar-95aaf',
    authDomain: 'ethmar-95aaf.firebaseapp.com',
    storageBucket: 'ethmar-95aaf.firebasestorage.app',
    measurementId: 'G-75810YRJVR',
  );
}
